version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: ./backend
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      DATABASE_URL: postgresql://user:password@db/dbname
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  db_data:
